@startuml
skinparam backgroundcolor transparent

'== Assets =='

'-- Javanile --'
artifact "www.javanile.org"
artifact "github.com/javanile"

'-- Francesco Bianco --'
artifact "github.com/francescobianco"
artifact "hardcode.blog"

'== Connections =='

[www.javanile.org] --> [github.com/javanile]

@enduml
