@startuml
skinparam monochrome reverse
skinparam backgroundcolor transparent

'== Assets =='

'-- Javanile --'
card "www.javanile.org"
card "github.com/javanile"

'-- Francesco Bianco --'
card "github.com/francescobianco"
card "twitter.com/francescobianco"
card "hardcode.blog"

'== Connections =='

[www.javanile.org] --> [github.com/javanile]
[twitter.com/francescobianco] --> [github.com/francescobianco]

[github.com/francescobianco] --> [hardcode.blog]

@enduml
